//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class VinceFramework_AppConstWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(VinceFramework.AppConst), typeof(System.Object));
		L.RegFunction("New", _CreateVinceFramework_AppConst);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("DebugMode", 0);
		L.RegVar("AppName", get_AppName, null);
		L.RegVar("LuaDirName", get_LuaDirName, null);
		L.RegVar("FrameworkRoot", get_FrameworkRoot, null);
		L.RegVar("LuaFileRoot", get_LuaFileRoot, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateVinceFramework_AppConst(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				VinceFramework.AppConst obj = new VinceFramework.AppConst();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: VinceFramework.AppConst.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AppName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, VinceFramework.AppConst.AppName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaDirName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, VinceFramework.AppConst.LuaDirName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FrameworkRoot(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, VinceFramework.AppConst.FrameworkRoot);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaFileRoot(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, VinceFramework.AppConst.LuaFileRoot);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

