---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2020/3/26 10:41
---
local HintDialogueModel = {}
--字幕滚动时间
HintDialogueModel.doTextSpeed = 0.03
--字幕播放状态
HintDialogueModel.doTextStateCfg =
{
    none = 0, --无状态
    doText = 1, --开始字幕
    doTextEnd = 2, --字幕结束
}

--提示对话的显示方向
HintDialogueModel.direction_right = "right"
HintDialogueModel.direction_left = "left"

--提示对话的显示位置
HintDialogueModel.posCfg =
{
    pos_left_1 = 1,
    pos_left_2 = 2,
    pos_left_3 = 3,
    pos_left_4 = 4,
    pos_right_1 = 5,
    pos_right_2 = 6,
    pos_right_3 = 7,
    pos_right_4 = 8,
}

--位置对应方向
HintDialogueModel.posToDirCfg =
{
    [HintDialogueModel.posCfg.pos_left_1] = HintDialogueModel.direction_left,
    [HintDialogueModel.posCfg.pos_left_2] = HintDialogueModel.direction_left,
    [HintDialogueModel.posCfg.pos_left_3] = HintDialogueModel.direction_left,
    [HintDialogueModel.posCfg.pos_left_4] = HintDialogueModel.direction_left,
    [HintDialogueModel.posCfg.pos_right_1] = HintDialogueModel.direction_right,
    [HintDialogueModel.posCfg.pos_right_2] = HintDialogueModel.direction_right,
    [HintDialogueModel.posCfg.pos_right_3] = HintDialogueModel.direction_right,
    [HintDialogueModel.posCfg.pos_right_4] = HintDialogueModel.direction_right,
}



-----------------------------player config-------------------------------

HintDialogueModel.buffAutoMerge_putFire =
{
    {
        talker = TalkerConfig.Madelyn,
        pos = HintDialogueModel.posCfg.pos_right_2,
        content = "Merging workers to Level 5 will Inspire other workers Auto Merge.",
    },
}

HintDialogueModel.celebration =
{
    {
        talker = TalkerConfig.Madelyn,
        pos = HintDialogueModel.posCfg.pos_right_2,
        content = "The celebration lasts until midnight...",
    },
}

HintDialogueModel.dialogue_test =
{
    {
        talker = TalkerConfig.Madelyn,
        pos = HintDialogueModel.posCfg.pos_right_2,
        content = "Use him to put out the fires!",
    },
    {
        talker = TalkerConfig.Madelyn,
        pos = HintDialogueModel.posCfg.pos_left_2,
        content = "Use him to put out the fires!",
    },
}

HintDialogueModel.sword_guide =
{
    {
        talker = TalkerConfig.Madelyn,
        pos = HintDialogueModel.posCfg.pos_right_3,
        content = "每次拔剑需要重新合成3个工人!",
    },
}

return HintDialogueModel