---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/9/5 17:51
---

LuaHelper = VinceFramework.LuaHelper

resMgr = LuaHelper.GetResManager()

GameObject = UnityEngine.GameObject
Rect = UnityEngine.Rect
Sprite = UnityEngine.Sprite
Shader = UnityEngine.Shader
Material = UnityEngine.Material
Screen = UnityEngine.Screen
ScreenCapture = UnityEngine.ScreenCapture
Application = UnityEngine.Application
Camera = UnityEngine.Camera
Input = UnityEngine.Input
Physics = UnityEngine.Physics
Random = UnityEngine.Random
Time = UnityEngine.Time

DOTWEEN_EASE = DG.Tweening.Ease ---@type DG.Tweening.Ease
DOTWEEN_LOOP_TYPE = DG.Tweening.LoopType ---@type DG.Tweening.LoopType