---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiasm.
--- DateTime: 2021/8/10 15:26
---

local GuideEvent = class("MergeEvent", Event)



--=------------------------------[ static ]------------------------------=--

--- 引导相关
GuideEvent.GUIDE_CONTINUE = "ContinueGuide" ---引导继续
GuideEvent.INIT_TARGET_EVENT = "InitTargetEvent" ---引导对象设置完成初
GuideEvent.GATE_TASK_FIN_EVENT = "FinishGateTask"
GuideEvent.BLACKSMITH = "BLACKSMITH"
GuideEvent.FEED_DRAGON_GUIDE_OVER = "FeedDragonGuideOver"

--=----------------------------------------------------------------------=--



--
return GuideEvent