---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2020/12/21 14:34
--- 引导命令：延时
---@class Guide.Action.GuideDelay:Guide.Action.BaseGuideAction
---@field actionVo Guide.ActionData.GuideDelayVo
local GuideDelay = class("Guide.Action.GuideDelay", BaseGuideAction)

function GuideDelay:Ctor()
    GuideDelay.super.Ctor(self)
end

function GuideDelay:Execute()
    GuideDelay.super.Execute(self)
    if self.actionVo == nil then
        return
    end
    local delayTime = self.actionVo.delayTime
    local delayFrame = self.actionVo.delayFrame
    local isResume = self.actionVo.isResume
    if delayTime and delayTime > 0 then
        if self.actionVo.noModal ~= true then
            GuideController.GuideShowModal()
        end
        self.delay = DelayedCall(delayTime, function()
            if isResume == nil or isResume == true then
                GuideController.GuideHideModal(self.actionVo.resumeMerge)
            end
            self.delay = nil
            self:ActionEnd()
        end)
    elseif delayFrame and delayFrame > 0 then
        if self.actionVo.noModal ~= true then
            GuideController.GuideShowModal()
        end
        self.delay = DelayedFrameCall(function()
            if isResume == nil or isResume == true then
                GuideController.GuideHideModal(self.actionVo.resumeMerge)
            end
            self.delay = nil
            self:ActionEnd()
        end, delayFrame)
    else
        logWarning(string.format("GuideDelay的延迟时间配错 delayTime %s, delayFrame %s", tostring(delayTime), tostring(delayFrame)))
    end
end

--function GuideDelay:SkipCallback()
--    GuideDelay.super.SkipCallback(self)
--    if self.delay then
--        CancelDelayedCall(self.delay)
--        self.delay = nil
--    end
--    self:ActionEnd()
--end

return GuideDelay

---@class Guide.ActionData.GuideDelayVo
---@field delayTime number 延迟时间
---@field delayFrame number 延迟帧数
---@field isResume boolean 是否恢复
---@field resumeMerge boolean 是否恢复合成