---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2021/7/22 13:49
--- 引导命令：剧情演示
--- 剧情的实现创建为单独的lua文件 创建在Guide.Performance下 继承于BasePerformance 命名用 "Performance"为后缀

---@class Guide.Action.GuidePerformance:Guide.Action.BaseGuideAction
---@field actionVo Guide.ActionData.GuidePerformanceVo
local GuidePerformance = class("Guide.Action.GuidePerformance", BaseGuideAction)

function GuidePerformance:Ctor()
    GuidePerformance.super.Ctor(self)
end

function GuidePerformance:Execute()
    GuidePerformance.super.Execute(self)
    if self.actionVo == nil then
        return
    end
    local guidePath = string.format("Module.Guide.Performance.%sPerformance", tostring(self.actionVo.performanceName))
    if not Res.LuaFileExists(guidePath) then
        GuideData.DebugWarningLog(GuideData.NO_PER_GUIDE_ERROR, self.actionVo.performanceName)
        return
    end
    self.endHandler = handler(self.ActionEnd, self)
    self.performance = require(guidePath).New(self.actionVo.performanceName, self.endHandler) ---@type Guide.Performance.BasePerformance
    self.performance:Execute()
end

function GuidePerformance:SkipCallback()
    GuidePerformance.super.SkipCallback(self)
    if self.performance then
        self.performance:Skip()
    end
end

return GuidePerformance

---@class Guide.ActionData.GuidePerformanceVo
---@field performanceName string 剧情文件路径