---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2020/10/20 14:14
--- 引导命令：回调函数
---@class Guide.Action.GuideCallBack:Guide.Action.BaseGuideAction
---@field actionVo Guide.ActionData.GuideCallBackVo
local GuideCallBack = class("Guide.Action.GuideCallBack", BaseGuideAction)

function GuideCallBack:Ctor()
    GuideCallBack.super.Ctor(self)
end

function GuideCallBack:Execute()
    GuideCallBack.super.Execute(self)
    if self.actionVo == nil then
        return
    end
    if self.actionVo.callback then
        self.actionVo.callback()
    elseif self.actionVo.Callback then
        self.actionVo.Callback()
    else
        logWarning(string.format(GuideData.CALL_BACK_ERROR, GuideData.curGuideName, GuideData.curGuideIndexs))
    end

    self:ActionEnd()
end

--function GuideCallBack:SkipCallback()
--    GuideCallBack.super.SkipCallback(self)
--    self:ActionEnd()
--end

return GuideCallBack

---@class Guide.ActionData.GuideCallBackVo
---@field callback function 回调函数
---@field skipCallback function 跳过析构函数