---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2021/6/1 13:24
---
local prefab = "Prefabs/Guide/GuideBlackEndView.prefab"
---@class Guide.View.GuideBlackEndView:View
---@field New fun():Guide.View.GuideArrowMaskView
local GuideBlackEndView = class("Guide.View.GuideBlackEndView", View)
function GuideBlackEndView:Ctor(data)
    self.data =data
    GuideBlackEndView.super.Ctor(self, prefab, Constants.LAYER_GUIDE)
end

function GuideBlackEndView:OnInitialize()
    GuideBlackEndView.super.OnInitialize(self)
    self.cg = GetComponent.CanvasGroup(self.gameObject)
    self.text1 = GetComponent.Text(self.transform:Find("Text1").gameObject)
    self.text2 = GetComponent.Text(self.transform:Find("Text2").gameObject)
    self.cg.alpha = 0
    self.text1Str = self.data.text1 or self.text1.text
    self.text2Str = self.data.text2 or self.text2.text
    self.text1.text = ""
    self.text2.text = ""

    if self.data.tween then
        --self.text1.transform.localScale = Vector3.New(2.5,2.5,2.5)
        self.text1.text = self.text1Str
        local sequence = DOTween.Sequence()
        sequence:Append(self.cg:DOFade(1, 0.5))
        --sequence:Append(self.text1.transform:DOScale(1, 0.2):SetEase(DOTween_Enum.Ease.InQuart))
        sequence:AppendCallback(function()
            self.text1.gameObject:SetActive(true)
            GetComponent.DOTweenAnimation(self.text1.gameObject).enabled = true
            --self.text1.gameObject:GetComponent(typeof(DG.Tweening.DOTweenVisualManager)).enabled = true
        end)
        sequence:Append(self.text2:DOText(self.text2Str, #self.text2Str / 15))
        sequence:AppendCallback(function()
            DispatchEvent(GuideData, GuideEvent.GUIDE_CONTINUE)
        end)
    else
        local sequence = DOTween.Sequence()
        sequence:Append(self.cg:DOFade(1, 0.5))
        sequence:Append(self.text1:DOText(self.text1Str, #self.text1Str / 15))
        sequence:Append(self.text2:DOText(self.text2Str, #self.text2Str / 15))
        sequence:AppendCallback(function()
            DispatchEvent(GuideData, GuideEvent.GUIDE_CONTINUE)
        end)
    end
end

return GuideBlackEndView