---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2020/3/25 18:05
---
local HintDialogueModel = require("Module.Guide.Model.HintDialogueModel")
local prefab = "Prefabs/HintDialogue/HintDialogueItem.prefab"

---@class HintDialogueItem:View
---@field New fun():HintDialogueItem
---@field Root UnityEngine.GameObject
---@field iconRoot UnityEngine.GameObject
---@field dialogueRoot UnityEngine.GameObject
---@field pic UnityEngine.UI.Image
---@field nameText UnityEngine.UI.Text
---@field dialogueText UnityEngine.UI.Text
---@field info HintDialogueItem.HintDialogueConfig
local HintDialogueItem = class("HintDialogueItem", View)

HintDialogueItem.childPosCfg =
{
    [HintDialogueModel.direction_left] =
    {
        root = Vector3.New(320, 0, 0),
        iconRoot = Vector3.New(-220, 0, 0),
        dialogueRoot = Vector3.New(50, 0, 0)
    },
    [HintDialogueModel.direction_right] =
    {
        root = Vector3.New(-320, 0, 0),
        iconRoot = Vector3.New(220, 0, 0),
        dialogueRoot = Vector3.New(-50, 0, 0)
    },
}

function HintDialogueItem:Ctor(info, parent)
    self.info = info
    HintDialogueItem.super.Ctor(self, prefab, parent)
end

function HintDialogueItem:OnInitialize()
    HintDialogueItem.super.OnInitialize(self)
    self.Root = self.transform:Find("Root").gameObject
    self.iconRoot = self.transform:Find("Root/iconRoot").gameObject
    self.pic = GetComponent.Image(self.transform:Find("Root/iconRoot/pic").gameObject)
    self.nameText = GetComponent.Text(self.transform:Find("Root/iconRoot/nameText").gameObject)
    self.dialogueRoot = self.transform:Find("Root/dialogueRoot").gameObject
    self.dialogueText = GetComponent.Text(self.transform:Find("Root/dialogueRoot/bg/dialogueText").gameObject)

    self.enterDuration = 0.4
    self.leaveDuration = 0.25
    self.isChangeDir = false
    self:RefreshFacade()
end

function HintDialogueItem:RefreshFacade(info)

    if info == nil then
        --初始化
        self.direction = HintDialogueModel.posToDirCfg[self.info.pos]
        local posCfg = HintDialogueItem.childPosCfg[self.direction]
        self.Root.transform.localPosition = posCfg.root
        self.iconRoot.transform.localPosition = posCfg.iconRoot
        self.dialogueRoot.transform.localPosition = posCfg.dialogueRoot
        self.pic.sprite = Res.LoadSprite("Textures/UI/HalfPic/" .. self.info.talker.halfPic .. ".png")
        self.nameText.text = self.info.talker.name
    else
        --刷新
        local direction = HintDialogueModel.posToDirCfg[info.pos]
        if direction ~= self.direction then
            self.direction = direction
            local posCfg = HintDialogueItem.childPosCfg[direction]
            self.Root.transform.localPosition = posCfg.root
            self.iconRoot.transform.localPosition = posCfg.iconRoot
            self.dialogueRoot.transform.localPosition = posCfg.dialogueRoot
        end
        if info.talker.halfPic ~= self.info.talker.halfPic then
            self.pic.sprite = Res.LoadSprite("Textures/UI/HalfPic/" .. self.info.talker.halfPic .. ".png")
        end
        if info.talker.name ~= self.info.talker.name then
            self.nameText.text = info.talker.name
        end
        self.info = info
    end
    self.textDuration = string.len(self.info.content) * HintDialogueModel.doTextSpeed
    self.dialogueText.text = ""
end


--开始执行DoText
function HintDialogueItem:StartDoText(endCall)
    self.endCall = endCall
    self.textTween = self.dialogueText:DOText(self.info.content, self.textDuration, true, DOTween_Enum.ScrambleMode.None, nil)
            :SetEase(DOTween_Enum.Ease.Linear):OnComplete(function()
        if self.endCall then
            self.endCall()
        end

    end)
end

--结束DoText 显示全部文字
function HintDialogueItem:EndDoText()
    if self.textTween then
        self.textTween:Kill(false)
    end
    self.endCall = nil
    self.dialogueText.text = self.info.content
end

--进入效果
function HintDialogueItem:EnterTweenShow()
    if self.leaveTween then
        self.leaveTween:Kill(false)
    end
    local rootPos = HintDialogueItem.childPosCfg[self.direction].root
    self.Root.transform.localPosition = Vector3.New(-rootPos.x, 0, 0)
    self.enterTween = DOTween.Sequence()
    self.enterTween:Append(self.Root.transform:DOLocalMove(rootPos, self.enterDuration):SetEase(DOTween_Enum.Ease.InCubic))
end

--离开效果
function HintDialogueItem:LeaveTween()
    if self.enterTween then
        self.enterTween:Kill(false)
    end
    local rootPos = HintDialogueItem.childPosCfg[self.direction].root
    local endPos = Vector3.New(-rootPos.x, 0, 0)
    self.leaveTween = DOTween.Sequence()
    self.leaveTween:Append(self.Root.transform:DOLocalMove(endPos, self.leaveDuration):SetEase(DOTween_Enum.Ease.InCubic))
end

function HintDialogueItem:OnDestroy()
    HintDialogueItem.super.OnDestroy(self)
    if self.textTween then
        self.textTween:Kill()
    end
    if self.enterTween then
        self.enterTween:Kill()
    end
    if self.leaveTween then
        self.leaveTween:Kill()
    end
end

return HintDialogueItem

---@class HintDialogueItem.HintDialogueConfig 叙述内容配置
---@field talker Common.Talk.TalkerConfig @ 叙述者配置
---@field content string @ 叙述内容
---@field pos number @ -出现位置 配置HintDialogueModel.posCfg 默认：HintDialogueModel.posCfg.pos_left_2